# docker/vllm/Dockerfile.base
FROM nvidia/cuda:12.1.0-devel-ubuntu22.04

RUN apt update && apt install -y \
    python3 python3-pip python3-venv \
    git wget gcc \
 && apt clean \
 && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python

# pip 캐시 사용
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade pip \
 && pip install vllm torch transformers accelerate

WORKDIR /workspace
